### ISSUE TITLE
Request for butterflies logo

### ISSUE THREAD

**Issue by melezhik** [enjeck/libre-logos#2]
Hi! First of all great work, I wrote my review on maybe.io for your project - https://mybf.io/project/LibreLogos/reviews 

Is it possible to request a butterfly log for the  site? ))

Thanks

PS It's ok if you for some reasons it's not possible, I am just asking ...

**Comment by enjeck** [comment]
Hi @melezhik . These logos are meant for active open source projects and NGOS. Do you have one? 
Thanks for the review, by the way.

**Comment by melezhik** [comment]
Hi! This is mybf.io itself ...

**Comment by enjeck** [comment]
@melezhik Is there a git repository for the site? It doesn't seem to be open source. If it is, it has to be active project too (that is,  with regular commits or users). Logos are limited, and I want to make sure that projects that get it are quite active. 

Sorry for the delay, by the way. I'm still trying to figure out licensing, how to organize this project and what criteria to use for eligible projects.

**Comment by melezhik** [comment]
@enjeck this is opensource project in a sense it's not commercial now, the source code for some reasons in a private repository ... you could see activity of the project by reading new reviews appearing on the web site ...

**Comment by melezhik** [comment]
@enjeck  actually here is the link - https://github.com/melezhik/mybfio
