### ISSUE TITLE
Logo request

### ISSUE THREAD

**Issue by Juanpetecnica** [enjeck/libre-logos#32]
**To claim a logo, please fill the template below. If you have a feature request or bug report, [open a blank issue](https://github.com/enjeck/libre-logos/issues/new).**

--------------

##### For open source projects
- [ x] There are regular commits to my project
- [ ] My project has more than one contributor
- [ ]  My project has over 100 GitHub stars
- [ ]  The git history of my project spans over 1 year

##### For NGOs
- [ ] My organization is registered in at least one country
- [ ] My organization has been existing for over one year

#### Name of your project/organisation:
antipodas
#### Link to git repository and/or website:
https://github.com/Juanpetecnica/antipodas
#### Brief description of your project:
who is on the other side of our world
#### What logo do you want? Provide a link to it:
https://www.librelogos.org/logo/16

**Comment by enjeck** [comment]
Sorry, but your project does not satisfy enough eligibility requirements. If this changes at some point in the future, feel free to make another request. Thanks
