### ISSUE TITLE
Write a contributing guide

### ISSUE THREAD

**Issue by enjeck** [enjeck/libre-logos#4]
To invite designers to contribute their designs to the collection, it'll be helpful to have a contributing guide. It should include:
- What counts as a good logo
- Brief explanation of the structure of the project and where and how to add a logo to the collection
- What sort of files are required

**Comment by DelayCoderz** [comment]
@enjeck can i do this task ??

**Comment by enjeck** [comment]
@DelayCoderz Sure. Go for it :)

**Comment by enjeck** [comment]
@DelayCoderz  

You can decide to create a new contributing.md file or add it as a section in the readme. 
If you don't understand anything, feel free to ask me.

**Comment by DelayCoderz** [comment]
ok By the way, the contents of the guide only contain how to add images or
by changing the contents of the javascript file as well??

**Comment by enjeck** [comment]
> ok By the way, the contents of the guide only contain how to add images or
> by changing the contents of the javascript file as well??

Both. When a logo image is added to src/images/logos, data about the logo has to be added to src/data/logos.js.

**Comment by DelayCoderz** [comment]
@enjeck  I've finished it please see, if there is something missing I can replace it :)
