### ISSUE TITLE
Logo request

### ISSUE THREAD

**Issue by Lysxia** [enjeck/libre-logos#46]
**To claim a logo, please fill the template below. If you have a feature request or bug report, [open a blank issue](https://github.com/enjeck/libre-logos/issues/new).**

--------------

##### For open source projects
- [x] There are regular commits to my project
- [x] My project has more than one contributor
- [x]  My project has over 100 GitHub stars
- [x]  The git history of my project spans over 1 year

#### Name of your project:

Interaction Trees

#### Link to git repository and/or website:

https://github.com/DeepSpec/InteractionTrees/

#### Brief description of your project:

Library for representing recursive and impure languages in the Coq proof assistant

#### What logo do you want? Provide a link to it:

[Logo 11](https://www.librelogos.org/logo/11)

**Comment by enjeck** [comment]
It's yours! Here's the vector file: https://github.com/enjeck/libre-logos/blob/main/src/images/logos/svg/11-arrow-tree.svg
