### ISSUE TITLE
Logo request

### ISSUE THREAD

**Issue by NkululekoTech** [enjeck/libre-logos#50]
**To claim a logo, please fill the template below. If you have a feature request or bug report, [open a blank issue](https://github.com/enjeck/libre-logos/issues/new).**

--------------

##### For open source projects
- [ ] There are regular commits to my project
- [ ] My project has more than one contributor
- [ ]  My project has over 100 GitHub stars
- [ ]  The git history of my project spans over 1 year

##### For NGOs
- [x] My organization is registered in at least one country - Yes registered in South Africa
- [x] My organization has been existing for over one year - Yes but only formalised in 2023

#### What logo do you want? Provide a link to it: https://www.librelogos.org/logo/7
[COR14.3.pdf](https://github.com/enjeck/libre-logos/files/11067679/COR14.3.pdf)

**Comment by enjeck** [comment]
Closed via https://github.com/enjeck/libre-logos/commit/9370c927ee9c50de5234cdcb16afa35bb3eba6fc

**Comment by enjeck** [comment]
@NkululekoTech It's yours! You can download from: 
- https://github.com/enjeck/libre-logos/blob/main/src/images/logos/7-night-star.png
- https://github.com/enjeck/libre-logos/blob/main/src/images/logos/svg/7-night-star.svg
Thanks!

**Comment by TheCyberSensei** [comment]
Hi Cleopatra

Thank you for the links to the logo! You've just removed one stressful task
from my list.

Regards,
Nkululeko
